name: pelaicons
description: 1300+ icons. Designed by Pelateam
version: 0.0.1
homepage: https://github.com/stevenosse/pelaicons

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
     - family: Pelaicons
       fonts:
         - asset: fonts/pelaicons.ttf
