name: pelaicons
description: 1300+ icons. Designed by Pelateam
version: 1.0.0
homepage: https://github.com/stevenosse/pelaicons

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icon_font_generator: ^4.0.0

flutter:
  fonts:
     - family: Pelaicons
       fonts:
         - asset: fonts/pelaicons.otf

screenshots:
  - description: "Pelaicons cover preview"
    path: "cover.png"